### ISSUE TITLE
Investigación de bot

### ISSUE THREAD

**Issue by RT4DevSpace** [RT4DevSpace/PythonAutomatization#2]
Es necesario generar un bot que permita la interacción por mensaje en telegram y WA. 

## Objetivo
Realizar una investigación sobre las herramientas disponibles para crear bots de chat en Telegram y WA, las librerias necesarias y todos los requerimentos. Es necesario incluir un plan de trabajo para la implementación de las soluciones realizadas en el ticket de desarrollo.

## Resultados deseados
Un texto con los requerimentos especificados, un plan de acción que incluya los diagramas necesarios

**Comment by a-ceron** [comment]
# Investigación

Existen dos tipos de chatbots:
1. Basado en reglas: Es el más simple, barato e inmediato. Su objetivo es configurar un flujo que considere los diferentes escenarios de interacción con el cliente. Para su desarrollo la parte central es tener definido este diagrama de flujo que será la piedra angular por la que se defina el bot.
2. Basado en IA: Es más costoso y complejo de desarrollar pues se deben considerar el costo del token y las posibles rutas de acción de la IA, por otro lado si se quiere crear un propio modelo PLN es necesario contar con el equipo para realizar el entrenamiento y la base de datos para alimentar el modelo. 


## Resultados técnicos
Ya que el primer objetivo del proyecto es tener un bot de notificaciones, se iniciará con un bot basado en reglas que cumpla a la par la tarea de notificar sobre algún error y por otro lado dar un seguimiento de lo que el ingeniero haga o si requiere un escalamiento. 

### Características del desarrollo
1.  Lenguaje de programación: Python 3.11
2.  Bajo microservicios usando Docker y Kubernetes
3.  Sin base de datos, pero almacenando datos clave en CSV
4.  Librerias:
    * NLTK
    * Flask
    * scikit

Para el diseño del flujo se propone el siguiente flujo de trabajo inicial.


![Image](https://github.com/RT4DevSpace/PythonAutomatization/assets/40130391/a69180de-4f0b-48b3-9bc8-b8908c26a5e3)
