### ISSUE TITLE
Desarrollo de bot

### ISSUE THREAD

**Issue by RT4DevSpace** [RT4DevSpace/PythonAutomatization#3]
Desarrollar el bot para ambas plataforas Telegram y WA a partir del plan desarrollado en #2 

## Objetivo
Desarrollar el código necesario para implementar las soluciones establecidas en #2.

## Resultado deseado
Al termino de este ticket debe existir un programa/script o equivalente que realice envio de mensajes a ambas plataformas y a partir de las respuestas realizar diferentes acciones.

**Comment by a-ceron** [comment]
Iniciando con la creación del entorno de trabajo y los primeros pasos del chat bot. Algunas guias de apoyo que estaré usando.
- https://hackernoon.com/es/usando-flask-para-construir-un-chatbot-basado-en-reglas-en-python
- https://medium.com/@lurkinguard30/how-to-build-a-simple-chatbot-with-python-and-nltk-c1b9fff5f3
- https://prompt.uno/chatgpt/como-construir-un-chatbot-basado-en-reglas-usando-python-y-nltk/#google_vignette
- https://codigospython.com/creando-un-chat-con-pytchat-en-python-tutorial-completo/
